baseURL = "https://paulsoja.github.io/kotlintales/"
languageCode = "en-us"
title = "Kotlin Tales"
theme = "PaperMod"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
description = "Articles on advanced Kotlin, Android development, and software design."
defaultTheme = "light"
mainSections = ["posts"]

# верхнее меню
[menu]

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 2

[[menu.main]]
identifier = "subscribe"
name = "Subscribe"
url = "/subscribe/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4
