baseURL = "https://paulsoja.github.io/kotlintales/"
languageCode = "en-us"
title = "Kotlin Tales"
theme = "PaperMod"

[params]
  description = "Articles on advanced Kotlin, functional programming, and software design."
